<a href="https://colab.research.google.com/github/Nafew-I/NeurotechUofT-Contribution/blob/main/RNNmodelforEEGdata1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import SimpleRNN #used to create RNN
from google.colab import files
u = files.upload()

Saving S107R05.edf to S107R05.edf


In [ ]:
!pip install mne

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 19.1 MB/s eta 0:00:00


In [ ]:
#edf file: contains raw signals (i.e. EEG data). Shape is a 2D array determined by the number of channels(rows) and the number of time samples(columns)
#edf.events file: contains events associated with raw signals. Shape is a 2D array determined by the number of events(rows) and the number of columns needed to display the necessary event information
import mne
dataset = mne.io.read_raw_edf(list(u.keys())[0])#extracts raw eeg data
data = dataset.get_data() #filters out the data. Forms a 64x2000 array
events, event_id = mne.events_from_annotations(dataset) #extracts the events and the event IDs. Event info contains event id and duration of the event. Events is a 30x3 array which contains the onset time (shown in first element, it is the time index of the raw signal data, indicating when the event occured), duration (second element) and the event code (third element)
#Troubleshooting:
print(data)
print("")
print(events[25:])
print("")
print(event_id)


Extracting EDF parameters from /content/S107R05.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Used Annotations descriptions: ['T0', 'T1', 'T2']
[[ 1.52e-04  1.60e-04  1.47e-04 ...  0.00e+00  0.00e+00  0.00e+00]
 [ 1.33e-04  1.35e-04  1.29e-04 ...  0.00e+00  0.00e+00  0.00e+00]
 [ 1.45e-04  1.43e-04  1.37e-04 ...  0.00e+00  0.00e+00  0.00e+00]
 ...
 [-2.51e-04 -2.59e-04 -2.67e-04 ...  0.00e+00  0.00e+00  0.00e+00]
 [-3.10e-05 -3.90e-05 -4.10e-05 ...  0.00e+00  0.00e+00  0.00e+00]
 [-4.03e-04 -4.11e-04 -4.19e-04 ...  0.00e+00  0.00e+00  0.00e+00]]

[[16608     0     2]
 [17264     0     1]
 [17936     0     3]
 [18592     0     1]
 [19264     0     3]]

{'T0': 1, 'T1': 2, 'T2': 3}


In [ ]:
EEG_data = []
for i in 64-range(34):
  data.pop(i)
#train_input =
#train_output =
#test_input =
#test_output =

TypeError: unsupported operand type(s) for -: 'int' and 'range'

In [ ]:
EEG_model = Sequential()
EEG_model.add(Dense(70, input_shape(64,), activation = 'relu')) #input layer/May not work, if that's the case, remove and put input_shape in the simple RNN thingy
EEG_model.add(SimpleRNN(32, activation = 'relu')) #RNN layer
EEG_model.add(Dense(1, activation = 'relu')) #output layer
EEG_model.compile(loss = 'catagorical_crossentropy', optimizer = 'adam', metrics=['accuracy'])
EEG_model.fit()